### PR TITLE
integrate rc scripts in runit stages

### PR DESCRIPTION
**Pull request by udeved**
Recycle the old arch initscripts to boot and shutdown the system.
Add the sysvinit bootlogd.

A PKGBUILD to test the stuff is [here](https://github.com/artix-linux/artix-vcs/tree/master/runit-git).

issues:
* pkill needs more work on shutdown

```
Thu May  3 12:08:16 2018: :: Setting hostname: artix-laptop    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Adjusting system time and setting kernel time zone    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Creating list of required static device nodes    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Setting up tmpfiles.d entries for /dev    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Starting udev daemon    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Triggering udev uevents    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Loading user-specified modules    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Waiting for udev uevents to be processed    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Configuring virtual consoles    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Bringing up loopback interface    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Checking filesystems    [BUSY] artix: sauber, 398311/1610672 Dateien, 3215775/6430464 Blöcke
Thu May  3 12:08:16 2018: artix_boot: sauber, 365/655360 Dateien, 99282/2621440 Blöcke
Thu May  3 12:08:16 2018: fsck.fat 4.1 (2017-01-24)
Thu May  3 12:08:16 2018: /dev/sda1: 10 files, 65/65501 clusters
Thu May  3 12:08:16 2018: home: sauber, 207433/32768000 Dateien, 11973874/131072000 Blöcke
Thu May  3 12:08:16 2018: build: sauber, 618873/13107200 Dateien, 4602986/52428800 Blöcke
Thu May  3 12:08:16 2018: paccache: sauber, 2025/3276800 Dateien, 1892745/13107200 Blöcke
Thu May  3 12:08:16 2018:    [DONE] 
Thu May  3 12:08:16 2018: :: Remounting root and API filesystems    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Mounting local filesystems    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Activating swap    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Initializing random seed    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Setting up tmpfiles.d entries    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Setting up sysusers.d entries    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Saving dmesg log    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: :: Initialization complete    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: - runit: leave stage: /etc/runit/1
Thu May  3 12:08:16 2018: - runit: enter stage: /etc/runit/2
Thu May  3 12:08:16 2018: :: Running stage 2    [BUSY]    [DONE] 
Thu May  3 12:08:16 2018: runsvchdir: default: current.
Thu May  3 12:08:16 2018: starting up with netlink and the input layer
Thu May  3 12:08:16 2018: 1 rule loaded
Thu May  3 12:08:16 2018: waiting for events: event logging is off
Thu May  3 12:08:16 2018: nm-dispatcher: req:1 'hostname': new request (2 scripts)
Thu May  3 12:08:16 2018: nm-dispatcher: req:1 'hostname': start running ordered scripts...
Thu May  3 12:08:16 2018: Successfully initialized wpa_supplicant
Thu May  3 12:08:16 2018: client connected from 740[0:0]
Thu May  3 12:08:16 2018: 1 client rule loaded
Thu May  3 12:08:16 2018: client connected from 740[0:0]
Thu May  3 12:08:16 2018: 1 client rule loaded
Thu May  3 12:08:16 2018: kwalletd5: Checking for pam module
Thu May  3 12:08:16 2018: kwalletd5: Got pam-login param
Thu May  3 12:08:16 2018: kwalletd5: Waiting for hash on 15-
Thu May  3 12:08:16 2018: kwalletd5: waitingForEnvironment on: 18
Thu May  3 12:08:16 2018: kwalletd5: client connected
Thu May  3 12:08:16 2018: kwalletd5: client disconnected
```

### CODE REVIEW

**Comment by konimex** [comment]
Why would we integrate the initscripts again since we already replaced it with the contents inside `core-services`?

I would keep stage1 scripts to be separated for easier maintainability.

Also, sysvinit's bootlogd is GPL so it is incompatible with runit-artix.

**Comment by udeved** [comment]
Ok, then we make bootlogd a separate package.

Question is, do we want the rc stuff separated, eventually in a package, then it make sense to keep stages and rc separate. If we deploy it as one package, I find in the end just stage shell files better.

**Comment by konimex** [comment]
I would first like to hear your definition of "rc stuff" since I have no idea about it. I only view what's in `core-services` as stage 1 scripts.

bootlogd can be a separate package, we can add a simple check in stage 1 to check if bootlogd bin exists.

**Comment by udeved** [comment]
rc stuff is old arch initscripts adopted for runit with nice status output and coloring.
Booting with runit looks like arch used to look before systemd.
The stage scripts basically have assumed the function of the core- and shutdown-services. These could be deleted. I see no real gain by now to modularize them, since they are one shot anyway.

**Comment by konimex** [comment]
Modularizing them would ease the maintenance from our part instead of making a gigantic mess in the real stage 1 since they're all shell scripts anyway.

We can certainly adopt the status messages, though. They look nice.

I'll look into decoupling the non-essential scripts (lvm, cryptsetup, btrfs, etc.) into separate packages.

**Comment by udeved** [comment]
Better? :)

https://github.com/artix-linux/runit-artix/tree/rc-modules
https://github.com/artix-linux/bootlogd

**Pull request closed without merging**
